version: "3"

networks:
  default:
    driver: bridge

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: "nginx"
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/api
      - ./client:/var/www/client
    depends_on:
      - php
      - client
    networks:
      - default
  client:
    container_name: "client"
    image: "node:18-alpine"
    volumes:
      - ./client:/app
    working_dir: /app
    expose:
      - "3000"
    command: sh -c "npm run build && node ./.output/server/index.mjs"
    networks:
      - default
  php:
    container_name: "api"
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    expose:
      - "9000"
    networks:
      - default
    depends_on:
      - db
      - redis
  db:
    container_name: "db"
    image: mariadb:latest
    networks:
      - default
    ports:
      - "3336:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: poseidon
  redis:
    image: redis:latest
    container_name: "redis"
    command: [ "redis-server", "--bind", "0.0.0.0", "--port", "6379" ]
    restart: always
    hostname: 127.0.0.1
    networks:
      - default
    ports:
      - "6379:6379"
  phpmyadmin:
    container_name: "pma"
    image: phpmyadmin/phpmyadmin
    links:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
  mailhog:
    container_name: "mailhog"
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - default