version: "3"

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: "nginx"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/api
  php:
    container_name: "backend"
#    image: "php:8.2-fpm-alpine"
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api